name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: tudelft-cda-lab/FlexFringe/.github/workflows/build-test-all.yml@main
    secrets: inherit

  release-nightly:
    name: "Nightly release"
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/download-artifact@v3

      - name: "Rename"
        run: |
          ls -lah
          mv flexfringe-x64-windows flexfringe-x64-windows.exe 

      - name: "Publish"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            flexfringe-x64-linux
            flexfringe-x64-osx
            flexfringe-x64-windows.exe
